spring.application.name=granora

spring.datasource.url = ${DB_URL}
spring.datasource.username = ${DB_USUARIO}
spring.datasource.password = ${DB_SENHA}
## Hibernate Properties
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update