name: Metricas

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [ "main", "develop" ]


jobs:
  Metrica:
    name: Metricas
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: repository
          user: EduardaStef
          repo: granora-backend
          token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}