name: Metricas

on:
  push:
    branches: ["main"]


jobs:
  Metrica:
    name: Metricas
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: repository
          user: EduardaStef
          repo: granora-backend
          token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes